version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - run:
          name: Clone repo
          command: git clone https://github.com/martino-vic/gerstnerhungarian.git
      - run:
          name: Clone reference catalogues (takes 1min15s) & loanpy
          command: |
            mkdir concepticon
            cd concepticon
            git clone https://github.com/concepticon/concepticon-data.git
            cd ..
            git clone https://github.com/glottolog/glottolog.git
            git clone https://github.com/cldf-clts/clts.git
            git clone https://github.com/martino-vic/loanpy.git
      - run:
          name: install commands & download spacy word vector model
          command: |
            pip install -e gerstnerhungarian
            pip install -e loanpy
            python3 -m spacy download de_core_news_lg

      - run:
          name: shorten raw input
          command: cd gerstnerhungarian && cldfbench gerstnerhungarian.map
      - run:
          name: run lexibank script
          command: >
            cd gerstnerhungarian &&
            cldfbench lexibank.makecldf lexibank_gerstnerhungarian.py
            --concepticon-version=v2.5.0
            --glottolog-version=v4.5
            --clts-version=v2.2.0
      - run:
          name: Create orthography profile
          command: cd gerstnerhungarian && cldfbench gerstnerhungarian.makeortho
      - run:
          name: Rerun lexibank-script, from shell-script
          command: cd gerstnerhungarian && bash hun.sh
      - run:
          name: Install pytest
          command: pip install pytest-cldf
      - run:
          name: Test with pytest
          command: |
            cd gerstnerhungarian
            pytest --cldf-metadata=cldf/cldf-metadata.json test.py
      - run:
          name: Filter entries, check if output OK
          command: >
            cd gerstnerhungarian &&
            cldfbench gerstnerhungarian.filter

            cd loanpy && if diff hun0.tsv hun.tsv; then echo OK;
            else echo filtered files differ; exit 1; fi
      - run:
          name: Add reconstructions, check if output OK
          command: >
            cd gerstnerhungarian &&
            cldfbench gerstnerhungarian.reconstruct

            cd loanpy && if diff rchun0.tsv rchun.tsv; then echo OK;
            else echo reconstructions differ; exit 1; fi


workflows:
  main:
    jobs:
      - build
