version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  just-build:
    executor: python/default
    steps:
      - run:
          name: Install git
          command: |
            sudo apt install git

workflows:
  main:
    jobs:
      - just-build
