version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - run:
          name: Clone repo
          command: git clone https://github.com/martino-vic/gerstnerhungarian.git
#      - run:
#          name: Clone reference catalogues (takes 1min15s)
#          command: |
#            mkdir concepticon
#            cd concepticon
#            git clone https://github.com/concepticon/concepticon-data.git
#            cd ..
#            git clone https://github.com/glottolog/glottolog.git
#            git clone https://github.com/cldf-clts/clts.git
      - run:
          name: install commands
          command: pip install -e gerstnerhungarian
workflows:
  main:
    jobs:
      - build
