version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - run:
          name: Clone repo
          command: git clone https://github.com/martino-vic/gerstnerhungarian.git
      - run:
          name: Clone reference catalogues (takes 1min15s) & loanpy
          command: |
            mkdir concepticon
            cd concepticon
            git clone https://github.com/concepticon/concepticon-data.git
            cd ..
            git clone https://github.com/glottolog/glottolog.git
            git clone https://github.com/cldf-clts/clts.git
            git clone https://github.com/martino-vic/loanpy.git
            url="https://raw.githubusercontent.com/martino-vic/ronataswestoldturkic/main/loanpy/H2EAHsc.json"
            curl -s -L "$url" -o gerstnerhungarian/etc/H2EAHsc.json
      - run:
          name: install commands & download spacy word vector model
          command: |
            pip install -e gerstnerhungarian
            pip install -e loanpy
            python3 -m spacy download de_core_news_lg
      - run:
          name: shorten raw input
          command: >
            cd gerstnerhungarian &&
            cldfbench gerstnerhungarian.map
            --concepticon=../concepticon/concepticon-data
      - run:
          name: run lexibank script
          command: >
            cd gerstnerhungarian &&
            cldfbench lexibank.makecldf lexibank_gerstnerhungarian.py
            --concepticon-version=v2.5.0
            --glottolog-version=v4.5
            --clts-version=v2.2.0
            --concepticon=../concepticon/concepticon-data
            --glottolog=../glottolog
            --clts=../clts
      - run:
          name: Install pytest-cldf & check if dataset is CLDF conform
          command: |
            pip install pytest-cldf
            cd gerstnerhungarian
            pytest --cldf-metadata=cldf/cldf-metadata.json test.py
      - run:
          name: Update readme, filter entries, check if output OK
          command: >
            cd gerstnerhungarian &&
            cldfbench gerstnerhungarian.update_readme &&
            cldfbench gerstnerhungarian.filter

            file="loanpy/hun1416all.tsv" && lines=$(wc -l < "$file")

            if [ "$lines" -ne 1169 ];
            then echo length not 1169 lines but $lines; exit 1;
            else echo OK; fi

workflows:
  main:
    jobs:
      - build
